### ISSUE TITLE
Improve efficiency of Github CI checks

### ISSUE THREAD

**Issue by jasikpark** [DefinedNet/mobile_nebula#262]
Add these configs to where it makes sense:

```yaml
lint:
    name: Lint / Typecheck / Format check
    timeout-minutes: 10
    # Cancel in-progress jobs on the same branch
    concurrency:
      group: ${{ github.workflow }}-lint-${{ github.event.number || github.sha }}
      cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
```

This adds a max runtime for each job, and cancels jobs that are on the same branch, i.e. the same PR, *unless* it's the main branch.

This is useful to minimize the runtime of jobs and ensure the latest commit on a branch has up-to-date CI results ASAP.
