### ISSUE TITLE
Can't connect on ChromeOS; connecting results in crash

### ISSUE THREAD

**Issue by noseshimself** [DefinedNet/mobile_nebula#80]
After setting up a connection using the Android client on ChromeOS the aApplication seems to be crashing and I'm getting a pop-up from my Android subsystem.

![image](https://user-images.githubusercontent.com/6132793/200548255-a494be27-e3b7-4843-832b-44ab3f400374.png)

Rendered Config:
```
pki:
  ca: |
    -----BEGIN NEBULA CERTIFICATE-----
...
    -----END NEBULA CERTIFICATE-----
  cert: |
    -----BEGIN NEBULA CERTIFICATE-----
...
    -----END NEBULA CERTIFICATE-----
  key: <hidden>
  blacklist: []
static_host_map:
  172.31.247.254:
  - lighthouse.nebula.bnc.net:4246
lighthouse:
  am_lighthouse: false
  serve_dns: false
  dns:
    host: ""
    port: 0
  interval: 0
  hosts:
  - 172.31.247.254
listen:
  host: 0.0.0.0
  port: 0
  batch: 64
  read_buffer: 0
  write_buffer: 0
punchy:
  punch: true
  respond: false
  delay: 1s
cipher: aes
local_range: ""
sshd:
  enabled: false
  listen: ""
  host_key: ""
  authorized_users: []
tun:
  dev: tun1
  drop_local_broadcast: true
  drop_multicast: true
  tx_queue: 500
  mtu: 1300
  routes: []
  unsafe_routes: []
logging:
  level: info
  format: text
stats:
  type: ""
  interval: ""
  prefix: ""
  protocol: ""
  host: ""
  listen: ""
  path: ""
  namespace: ""
  subsystem: ""
handshakes:
  try_interval: 100ms
  retries: 20
  wait_rotation: 5
firewall:
  conntrack:
    tcp_timeout: 120h
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000
  outbound:
  - port: any
    proto: any
    host: any
  inbound: []
relays:
  use_relays: true
```

I can't deliver logs but the error message when trying to access logs might be a hint in itself:

![image](https://user-images.githubusercontent.com/6132793/200547239-b000edd4-153d-4218-928f-94fc94c4c4b7.png)

I sent an Android Feedback report but other developers already told me that Google is not reliably forwarding them to developers... Neither can I export the Android Feedback Report except as screen shots:

![image](https://user-images.githubusercontent.com/6132793/200550788-aa669615-45fe-4a6e-aa16-8d49635f8895.png)

![image](https://user-images.githubusercontent.com/6132793/200550440-b0900011-eee7-4462-b846-265f33c73785.png)

Event log:
![image](https://user-images.githubusercontent.com/6132793/200551240-87970ac6-f5bb-428e-9337-60b33ef28414.png)
![image](https://user-images.githubusercontent.com/6132793/200551360-eeb7ad5d-065a-49b9-b1da-eb01701ca8d1.png)

It might be a good idea to leave the user the choice of writing the logs to a location below /storage/emulated/0 for easier access during development, maybe marking that as "insecure mode".
